const express = require('express');
const session = require('express-session');
const bcrypt = require('bcryptjs');
const path = require('path');
const Database = require('better-sqlite3');
const moment = require('moment');
const app = express();
const PORT = process.env.PORT || 3000;
const db = new Database('database.db');